[package]
name = "rasn"
version = "0.0.0"
authors = ["Erin Power <xampprocky@gmail.com>"]
edition = "2018"
description = "Something someday."
license = "MIT/Apache-2.0"

[dependencies]
nom = "5"
num-bigint = "0.3.0"
num-traits = "0.2.12"
snafu = "0.6.8"
