[package]
name = "rasn-derive"
version = "0.2.0"
categories = ["encoding", "no-std", "parser-implementations"]
authors = ["Erin Power <xampprocky@gmail.com>"]
edition = "2018"
description = "Derive macros for rasn."
license = "MIT/Apache-2.0"
exclude = ["fuzzing"]
keywords = ["asn1", "der", "ber", "cer", "per"]
repository = "https://github.com/XAMPPRocky/rasn.git"

[lib]
proc-macro = true

[dependencies]
syn = "1.0.39"
quote = "1.0.7"
proc-macro2 = "1.0.19"
phf_codegen = "0.8.0"
